// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/Author.ts";
import * as $$$4 from "./loaders/Blogpost.ts";
import * as $$$1 from "./loaders/BlogPostItem.ts";
import * as $$$5 from "./loaders/BlogpostList.ts";
import * as $$$6 from "./loaders/BlogpostListing.ts";
import * as $$$2 from "./loaders/BlogPostPage.ts";
import * as $$$3 from "./loaders/BlogRelatedPosts.ts";
import * as $$$7 from "./loaders/Category.ts";
import * as $$$8 from "./loaders/GetCategories.ts";
import * as $$$$$$0 from "./sections/Blog/BlogPosts.tsx";
import * as $$$$$$1 from "./sections/Blog/BlogTemplate.tsx";
import * as $$$$$$3 from "./sections/Blog/components/ImageAndTextSection.tsx";
import * as $$$$$$4 from "./sections/Blog/components/ImageThreeColumnSection.tsx";
import * as $$$$$$5 from "./sections/Blog/components/ImageTwoColumnSection.tsx";
import * as $$$$$$6 from "./sections/Blog/components/OneImage.tsx";
import * as $$$$$$7 from "./sections/Blog/components/TextSectionBlog.tsx";
import * as $$$$$$8 from "./sections/Blog/components/VideoSection.tsx";
import * as $$$$$$2 from "./sections/Blog/MainPost.tsx";
import * as $$$$$$9 from "./sections/Seo/SeoBlogPost.tsx";
import * as $$$$$$10 from "./sections/Seo/SeoBlogPostListing.tsx";
import * as $$$$$$11 from "./sections/Template.tsx";

const manifest = {
  "loaders": {
    "site/loaders/Author.ts": $$$0,
    "site/loaders/Blogpost.ts": $$$4,
    "site/loaders/BlogPostItem.ts": $$$1,
    "site/loaders/BlogpostList.ts": $$$5,
    "site/loaders/BlogpostListing.ts": $$$6,
    "site/loaders/BlogPostPage.ts": $$$2,
    "site/loaders/BlogRelatedPosts.ts": $$$3,
    "site/loaders/Category.ts": $$$7,
    "site/loaders/GetCategories.ts": $$$8,
  },
  "sections": {
    "site/sections/Blog/BlogPosts.tsx": $$$$$$0,
    "site/sections/Blog/BlogTemplate.tsx": $$$$$$1,
    "site/sections/Blog/components/ImageAndTextSection.tsx": $$$$$$3,
    "site/sections/Blog/components/ImageThreeColumnSection.tsx": $$$$$$4,
    "site/sections/Blog/components/ImageTwoColumnSection.tsx": $$$$$$5,
    "site/sections/Blog/components/OneImage.tsx": $$$$$$6,
    "site/sections/Blog/components/TextSectionBlog.tsx": $$$$$$7,
    "site/sections/Blog/components/VideoSection.tsx": $$$$$$8,
    "site/sections/Blog/MainPost.tsx": $$$$$$2,
    "site/sections/Seo/SeoBlogPost.tsx": $$$$$$9,
    "site/sections/Seo/SeoBlogPostListing.tsx": $$$$$$10,
    "site/sections/Template.tsx": $$$$$$11,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
